# ------------------------ NGOXDB Configuration ------------------------


# ------------------------ master config        ------------------------

#master:
#  name: master,
#  database: <show all: ngoxdb -h>
#  host:
#  port:
#  database-name:
#  password:
#  params: <suchAs: mysql-extension-params: useSSL=false;...>
#  local-file: <path>
#  parallel-workers: <int, default: availableProcessors * 2>
#  thread-pool-size: <int, default: 0x7fffffff>
#  tables: <table_name1,table_name2,...>

# ------------------------ slave config(s)      ------------------------

# slave config(支持一个或多个)
#slave:
#  - {
#    name: slave1,
#    database: oracle,
#    servers: tcp://192.168.3.101:1521,192.168.3.104:1521,
#    database-name: sakila,
#    username: root,
#    password: xxxxxx,
#    replace-table: true,
#    truncate-table: true,
#    generate-name: true,
#    remap-table: <actor:actor2, film:film2>
#  }
#  - {
#    name: slave2,
#    database: msaccess,
    ##    host: <host>,
    ##    port: 3306,
    ##    servers: tcp://192.168.3.101:1521,192.168.3.104:1521,
    ##    database-name: sakila,
    ##    username: root,
    ##    password: xxxxxx,
    ##    replace-table: true,
    ##    truncate-table: true,
    ##    generate-name: true,
#    local-file: </tmp/sakila.mdb>,
#    new-database-version: <V2000, V2003, V2007, V2010>,
#    remap-table: <actor:actor2, film:film2>
#  }

#logging:
#  config: /Users/fei00/ngoxdb/release/config/logback.xml
#spring:
#  profiles:
#    active: dev
